#!/usr/bin/env bash
# Download
#    curl -Ls https://github.com/rikby/semversort/releases/download/0.1.0/semversort | bash
# And run:
#    $ semversort 1.0 1.0-rc 1.0-patch 1.0-alpha
# or in GIT
#    $ semversort $(git tag)
# Using pipeline:
#    $ echo 1.0 1.0-rc 1.0-patch 1.0-alpha | semversort
#
# 2016-11-03

set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

# Script running with pipeline executing
if [ -z "${BASH_SOURCE[0]:-}" ]; then
  __dir=/usr/local/bin
  if [ ! -d ${__dir} ]; then
    __dir=/usr/bin
  fi

  version=${1:-0.1.0}

  __file=${__dir}/semversort
  curl -Ls https://github.com/rikby/semversort/releases/download/${version}/semversort -o ${__file} && \
    chmod u+x ${__file} && \
    echo 'Semantic version sort: '${__file} && \
    exit 0
  exit 1
fi
